name: CI for zip project
on:
  push:
    branches:
      - main

jobs:
  zip:
    name: zip
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Zip file
        run: |
          ls -l
          zip -r src.zip src/
          ls
